// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("org.bukkit.Bukkit")
open class Bukkit: JavaObject {

}
extension JavaClass<Bukkit> {
  /// Java method `getName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getName()
  /// ```
@JavaStaticMethod
  public func getName() -> String

  /// Java method `shutdown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.shutdown()
  /// ```
@JavaStaticMethod
  public func shutdown()

  /// Java method `getPort`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getPort()
  /// ```
@JavaStaticMethod
  public func getPort() -> Int32

  /// Java method `broadcast`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.broadcast(java.lang.String,java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func broadcast(_ arg0: String, _ arg1: String) -> Int32

  /// Java method `reload`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.reload()
  /// ```
@JavaStaticMethod
  public func reload()

  /// Java method `getVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getVersion()
  /// ```
@JavaStaticMethod
  public func getVersion() -> String

  /// Java method `getResourcePackHash`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getResourcePackHash()
  /// ```
@JavaStaticMethod
  public func getResourcePackHash() -> String

  /// Java method `getSimulationDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getSimulationDistance()
  /// ```
@JavaStaticMethod
  public func getSimulationDistance() -> Int32

  /// Java method `clearBlockHighlights`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.clearBlockHighlights()
  /// ```
@JavaStaticMethod
  public func clearBlockHighlights()

  /// Java method `getMinecraftVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getMinecraftVersion()
  /// ```
@JavaStaticMethod
  public func getMinecraftVersion() -> String

  /// Java method `getGenerateStructures`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.getGenerateStructures()
  /// ```
@JavaStaticMethod
  public func getGenerateStructures() -> Bool

  /// Java method `getResourcePackPrompt`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getResourcePackPrompt()
  /// ```
@JavaStaticMethod
  public func getResourcePackPrompt() -> String

  /// Java method `isResourcePackRequired`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isResourcePackRequired()
  /// ```
@JavaStaticMethod
  public func isResourcePackRequired() -> Bool

  /// Java method `isWhitelistEnforced`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isWhitelistEnforced()
  /// ```
@JavaStaticMethod
  public func isWhitelistEnforced() -> Bool

  /// Java method `setWhitelistEnforced`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setWhitelistEnforced(boolean)
  /// ```
@JavaStaticMethod
  public func setWhitelistEnforced(_ arg0: Bool)

  /// Java method `getConnectionThrottle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static long org.bukkit.Bukkit.getConnectionThrottle()
  /// ```
@JavaStaticMethod
  public func getConnectionThrottle() -> Int64

  /// Java method `getTicksPerAnimalSpawns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getTicksPerAnimalSpawns()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getTicksPerAnimalSpawns() -> Int32

  /// Java method `getTicksPerMonsterSpawns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getTicksPerMonsterSpawns()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getTicksPerMonsterSpawns() -> Int32

  /// Java method `getTicksPerWaterSpawns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getTicksPerWaterSpawns()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getTicksPerWaterSpawns() -> Int32

  /// Java method `getTicksPerAmbientSpawns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getTicksPerAmbientSpawns()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getTicksPerAmbientSpawns() -> Int32

  /// Java method `shouldSendChatPreviews`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.shouldSendChatPreviews()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func shouldSendChatPreviews() -> Bool

  /// Java method `isEnforcingSecureProfiles`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isEnforcingSecureProfiles()
  /// ```
@JavaStaticMethod
  public func isEnforcingSecureProfiles() -> Bool

  /// Java method `isAcceptingTransfers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isAcceptingTransfers()
  /// ```
@JavaStaticMethod
  public func isAcceptingTransfers() -> Bool

  /// Java method `getHideOnlinePlayers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.getHideOnlinePlayers()
  /// ```
@JavaStaticMethod
  public func getHideOnlinePlayers() -> Bool

  /// Java method `getMaxChainedNeighborUpdates`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getMaxChainedNeighborUpdates()
  /// ```
@JavaStaticMethod
  public func getMaxChainedNeighborUpdates() -> Int32

  /// Java method `getMonsterSpawnLimit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getMonsterSpawnLimit()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getMonsterSpawnLimit() -> Int32

  /// Java method `getAnimalSpawnLimit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getAnimalSpawnLimit()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getAnimalSpawnLimit() -> Int32

  /// Java method `getWaterAnimalSpawnLimit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getWaterAnimalSpawnLimit()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getWaterAnimalSpawnLimit() -> Int32

  /// Java method `getAmbientSpawnLimit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getAmbientSpawnLimit()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getAmbientSpawnLimit() -> Int32

  /// Java method `getPauseWhenEmptyTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getPauseWhenEmptyTime()
  /// ```
@JavaStaticMethod
  public func getPauseWhenEmptyTime() -> Int32

  /// Java method `setPauseWhenEmptyTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setPauseWhenEmptyTime(int)
  /// ```
@JavaStaticMethod
  public func setPauseWhenEmptyTime(_ arg0: Int32)

  /// Java method `reloadCommandAliases`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.reloadCommandAliases()
  /// ```
@JavaStaticMethod
  public func reloadCommandAliases() -> Bool

  /// Java method `getPermissionMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getPermissionMessage()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getPermissionMessage() -> String

  /// Java method `getTicksPerWaterAmbientSpawns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getTicksPerWaterAmbientSpawns()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getTicksPerWaterAmbientSpawns() -> Int32

  /// Java method `getWaterAmbientSpawnLimit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getWaterAmbientSpawnLimit()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getWaterAmbientSpawnLimit() -> Int32

  /// Java method `getTickTimes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static long[] org.bukkit.Bukkit.getTickTimes()
  /// ```
@JavaStaticMethod
  public func getTickTimes() -> [Int64]

  /// Java method `getTPS`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static double[] org.bukkit.Bukkit.getTPS()
  /// ```
@JavaStaticMethod
  public func getTPS() -> [Double]

  /// Java method `getPlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.entity.Player org.bukkit.Bukkit.getPlayer(java.lang.String)
  /// ```
@JavaStaticMethod
  public func getPlayer(_ arg0: String) -> Player!

  /// Java method `getViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getViewDistance()
  /// ```
@JavaStaticMethod
  public func getViewDistance() -> Int32

  /// Java method `getAllowFlight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.getAllowFlight()
  /// ```
@JavaStaticMethod
  public func getAllowFlight() -> Bool

  /// Java method `getVersionMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getVersionMessage()
  /// ```
@JavaStaticMethod
  public func getVersionMessage() -> String

  /// Java method `getBukkitVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getBukkitVersion()
  /// ```
@JavaStaticMethod
  public func getBukkitVersion() -> String

  /// Java method `getMaxPlayers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getMaxPlayers()
  /// ```
@JavaStaticMethod
  public func getMaxPlayers() -> Int32

  /// Java method `setMaxPlayers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setMaxPlayers(int)
  /// ```
@JavaStaticMethod
  public func setMaxPlayers(_ arg0: Int32)

  /// Java method `getIp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getIp()
  /// ```
@JavaStaticMethod
  public func getIp() -> String

  /// Java method `getWorldType`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getWorldType()
  /// ```
@JavaStaticMethod
  public func getWorldType() -> String

  /// Java method `getMaxWorldSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getMaxWorldSize()
  /// ```
@JavaStaticMethod
  public func getMaxWorldSize() -> Int32

  /// Java method `getAllowEnd`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.getAllowEnd()
  /// ```
@JavaStaticMethod
  public func getAllowEnd() -> Bool

  /// Java method `getAllowNether`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.getAllowNether()
  /// ```
@JavaStaticMethod
  public func getAllowNether() -> Bool

  /// Java method `isLoggingIPs`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isLoggingIPs()
  /// ```
@JavaStaticMethod
  public func isLoggingIPs() -> Bool

  /// Java method `getResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getResourcePack()
  /// ```
@JavaStaticMethod
  public func getResourcePack() -> String

  /// Java method `hasWhitelist`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.hasWhitelist()
  /// ```
@JavaStaticMethod
  public func hasWhitelist() -> Bool

  /// Java method `setWhitelist`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setWhitelist(boolean)
  /// ```
@JavaStaticMethod
  public func setWhitelist(_ arg0: Bool)

  /// Java method `reloadWhitelist`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.reloadWhitelist()
  /// ```
@JavaStaticMethod
  public func reloadWhitelist()

  /// Java method `broadcastMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.broadcastMessage(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func broadcastMessage(_ arg0: String) -> Int32

  /// Java method `getUpdateFolder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getUpdateFolder()
  /// ```
@JavaStaticMethod
  public func getUpdateFolder() -> String

  /// Java method `getPlayerExact`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.entity.Player org.bukkit.Bukkit.getPlayerExact(java.lang.String)
  /// ```
@JavaStaticMethod
  public func getPlayerExact(_ arg0: String) -> Player!

  /// Java method `isTickingWorlds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isTickingWorlds()
  /// ```
@JavaStaticMethod
  public func isTickingWorlds() -> Bool

  /// Java method `unloadWorld`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.unloadWorld(java.lang.String,boolean)
  /// ```
@JavaStaticMethod
  public func unloadWorld(_ arg0: String, _ arg1: Bool) -> Bool

  /// Java method `reloadData`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.reloadData()
  /// ```
@JavaStaticMethod
  public func reloadData()

  /// Java method `updateResources`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.updateResources()
  /// ```
@JavaStaticMethod
  public func updateResources()

  /// Java method `updateRecipes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.updateRecipes()
  /// ```
@JavaStaticMethod
  public func updateRecipes()

  /// Java method `savePlayers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.savePlayers()
  /// ```
@JavaStaticMethod
  public func savePlayers()

  /// Java method `clearRecipes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.clearRecipes()
  /// ```
@JavaStaticMethod
  public func clearRecipes()

  /// Java method `resetRecipes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.resetRecipes()
  /// ```
@JavaStaticMethod
  public func resetRecipes()

  /// Java method `getSpawnRadius`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getSpawnRadius()
  /// ```
@JavaStaticMethod
  public func getSpawnRadius() -> Int32

  /// Java method `setSpawnRadius`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setSpawnRadius(int)
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func setSpawnRadius(_ arg0: Int32)

  /// Java method `getOnlineMode`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.getOnlineMode()
  /// ```
@JavaStaticMethod
  public func getOnlineMode() -> Bool

  /// Java method `isHardcore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isHardcore()
  /// ```
@JavaStaticMethod
  public func isHardcore() -> Bool

  /// Java method `banIP`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.banIP(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func banIP(_ arg0: String)

  /// Java method `unbanIP`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.unbanIP(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func unbanIP(_ arg0: String)

  /// Java method `createInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.inventory.Inventory org.bukkit.Bukkit.createInventory(org.bukkit.inventory.InventoryHolder,int,java.lang.String) throws java.lang.IllegalArgumentException
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func createInventory(_ arg0: InventoryHolder?, _ arg1: Int32, _ arg2: String) throws -> Inventory!

  /// Java method `createInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.inventory.Inventory org.bukkit.Bukkit.createInventory(org.bukkit.inventory.InventoryHolder,int) throws java.lang.IllegalArgumentException
  /// ```
@JavaStaticMethod
  public func createInventory(_ arg0: InventoryHolder?, _ arg1: Int32) throws -> Inventory!

  /// Java method `isPrimaryThread`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isPrimaryThread()
  /// ```
@JavaStaticMethod
  public func isPrimaryThread() -> Bool

  /// Java method `getMotd`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getMotd()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getMotd() -> String

  /// Java method `setMotd`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setMotd(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func setMotd(_ arg0: String)

  /// Java method `getShutdownMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getShutdownMessage()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getShutdownMessage() -> String

  /// Java method `setIdleTimeout`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.setIdleTimeout(int)
  /// ```
@JavaStaticMethod
  public func setIdleTimeout(_ arg0: Int32)

  /// Java method `getIdleTimeout`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getIdleTimeout()
  /// ```
@JavaStaticMethod
  public func getIdleTimeout() -> Int32

  /// Java method `getAverageTickTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static double org.bukkit.Bukkit.getAverageTickTime()
  /// ```
@JavaStaticMethod
  public func getAverageTickTime() -> Double

  /// Java method `reloadPermissions`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.reloadPermissions()
  /// ```
@JavaStaticMethod
  public func reloadPermissions()

  /// Java method `getCurrentTick`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getCurrentTick()
  /// ```
@JavaStaticMethod
  public func getCurrentTick() -> Int32

  /// Java method `isStopping`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isStopping()
  /// ```
@JavaStaticMethod
  public func isStopping() -> Bool

  /// Java method `isGlobalTickThread`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isGlobalTickThread()
  /// ```
@JavaStaticMethod
  public func isGlobalTickThread() -> Bool

  /// Java method `restart`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void org.bukkit.Bukkit.restart()
  /// ```
@JavaStaticMethod
  public func restart()

  /// Java method `getServerName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static java.lang.String org.bukkit.Bukkit.getServerName()
  /// ```
@JavaStaticMethod
  public func getServerName() -> String

  /// Java method `isLagging`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.isLagging()
  /// ```
@JavaStaticMethod
  public func isLagging() -> Bool

  /// Java method `getTicksPerWaterUndergroundCreatureSpawns`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getTicksPerWaterUndergroundCreatureSpawns()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getTicksPerWaterUndergroundCreatureSpawns() -> Int32

  /// Java method `getWaterUndergroundCreatureSpawnLimit`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static int org.bukkit.Bukkit.getWaterUndergroundCreatureSpawnLimit()
  /// ```
@available(*, deprecated)
  @JavaStaticMethod
  public func getWaterUndergroundCreatureSpawnLimit() -> Int32

  /// Java method `suggestPlayerNamesWhenNullTabCompletions`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean org.bukkit.Bukkit.suggestPlayerNamesWhenNullTabCompletions()
  /// ```
@JavaStaticMethod
  public func suggestPlayerNamesWhenNullTabCompletions() -> Bool
}
