// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("com.snj.EconomyManager")
open class EconomyManager: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<EconomyManager> {
  /// Java method `getBalance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static double com.snj.EconomyManager.getBalance(java.lang.String)
  /// ```
@JavaStaticMethod
  public func getBalance(_ arg0: String) -> Double

  /// Java method `withdraw`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static boolean com.snj.EconomyManager.withdraw(java.lang.String,double)
  /// ```
@JavaStaticMethod
  public func withdraw(_ arg0: String, _ arg1: Double) -> Bool
}
