// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("org.bukkit.inventory.InventoryHolder")
public struct InventoryHolder {
  /// Java method `getInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.Inventory org.bukkit.inventory.InventoryHolder.getInventory()
  /// ```
@JavaMethod
  public func getInventory() -> Inventory!
}
