// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("org.bukkit.inventory.Inventory")
public struct Inventory {
  /// Java method `remove`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.remove(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func remove(_ arg0: ItemStack?)

  /// Java method `clear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.clear(int)
  /// ```
@JavaMethod
  public func clear(_ arg0: Int32)

  /// Java method `clear`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.clear()
  /// ```
@JavaMethod
  public func clear()

  /// Java method `isEmpty`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.Inventory.isEmpty()
  /// ```
@JavaMethod
  public func isEmpty() -> Bool

  /// Java method `contains`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.Inventory.contains(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func contains(_ arg0: ItemStack?) -> Bool

  /// Java method `contains`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.Inventory.contains(org.bukkit.inventory.ItemStack,int)
  /// ```
@JavaMethod
  public func contains(_ arg0: ItemStack?, _ arg1: Int32) -> Bool

  /// Java method `first`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.Inventory.first(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func first(_ arg0: ItemStack?) -> Int32

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.Inventory.close()
  /// ```
@JavaMethod
  public func close() -> Int32

  /// Java method `getSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.Inventory.getSize()
  /// ```
@JavaMethod
  public func getSize() -> Int32

  /// Java method `getContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack[] org.bukkit.inventory.Inventory.getContents()
  /// ```
@JavaMethod
  public func getContents() -> [ItemStack?]

  /// Java method `setItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.setItem(int,org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func setItem(_ arg0: Int32, _ arg1: ItemStack?)

  /// Java method `getItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.inventory.Inventory.getItem(int)
  /// ```
@JavaMethod
  public func getItem(_ arg0: Int32) -> ItemStack!

  /// Java method `setMaxStackSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.setMaxStackSize(int)
  /// ```
@JavaMethod
  public func setMaxStackSize(_ arg0: Int32)

  /// Java method `getMaxStackSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.Inventory.getMaxStackSize()
  /// ```
@JavaMethod
  public func getMaxStackSize() -> Int32

  /// Java method `setContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.setContents(org.bukkit.inventory.ItemStack[]) throws java.lang.IllegalArgumentException
  /// ```
@JavaMethod
  public func setContents(_ arg0: [ItemStack?]) throws

  /// Java method `getStorageContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack[] org.bukkit.inventory.Inventory.getStorageContents()
  /// ```
@JavaMethod
  public func getStorageContents() -> [ItemStack?]

  /// Java method `setStorageContents`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.Inventory.setStorageContents(org.bukkit.inventory.ItemStack[]) throws java.lang.IllegalArgumentException
  /// ```
@JavaMethod
  public func setStorageContents(_ arg0: [ItemStack?]) throws

  /// Java method `containsAtLeast`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.Inventory.containsAtLeast(org.bukkit.inventory.ItemStack,int)
  /// ```
@JavaMethod
  public func containsAtLeast(_ arg0: ItemStack?, _ arg1: Int32) -> Bool

  /// Java method `firstEmpty`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.Inventory.firstEmpty()
  /// ```
@JavaMethod
  public func firstEmpty() -> Int32

  /// Java method `getHolder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.InventoryHolder org.bukkit.inventory.Inventory.getHolder(boolean)
  /// ```
@JavaMethod
  public func getHolder(_ arg0: Bool) -> InventoryHolder!

  /// Java method `getHolder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.InventoryHolder org.bukkit.inventory.Inventory.getHolder()
  /// ```
@JavaMethod
  public func getHolder() -> InventoryHolder!
}
