// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("org.bukkit.inventory.InventoryView")
public struct InventoryView {
  /// Java method `getTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.InventoryView.getTitle()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getTitle() -> String

  /// Java method `getTopInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.Inventory org.bukkit.inventory.InventoryView.getTopInventory()
  /// ```
@JavaMethod
  public func getTopInventory() -> Inventory!

  /// Java method `getBottomInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.Inventory org.bukkit.inventory.InventoryView.getBottomInventory()
  /// ```
@JavaMethod
  public func getBottomInventory() -> Inventory!

  /// Java method `setCursor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.InventoryView.setCursor(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func setCursor(_ arg0: ItemStack?)

  /// Java method `getCursor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.inventory.InventoryView.getCursor()
  /// ```
@JavaMethod
  public func getCursor() -> ItemStack!

  /// Java method `convertSlot`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.InventoryView.convertSlot(int)
  /// ```
@JavaMethod
  public func convertSlot(_ arg0: Int32) -> Int32

  /// Java method `countSlots`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.InventoryView.countSlots()
  /// ```
@JavaMethod
  public func countSlots() -> Int32

  /// Java method `getOriginalTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.InventoryView.getOriginalTitle()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getOriginalTitle() -> String

  /// Java method `setTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.InventoryView.setTitle(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setTitle(_ arg0: String)

  /// Java method `getInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.Inventory org.bukkit.inventory.InventoryView.getInventory(int)
  /// ```
@JavaMethod
  public func getInventory(_ arg0: Int32) -> Inventory!

  /// Java method `getItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.inventory.InventoryView.getItem(int)
  /// ```
@JavaMethod
  public func getItem(_ arg0: Int32) -> ItemStack!

  /// Java method `setItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.InventoryView.setItem(int,org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func setItem(_ arg0: Int32, _ arg1: ItemStack?)

  /// Java method `close`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.InventoryView.close()
  /// ```
@JavaMethod
  public func close()

  /// Java method `open`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.InventoryView.open()
  /// ```
@JavaMethod
  public func open()
}
extension JavaClass<InventoryView> {
  @JavaStaticField(isFinal: true)
  public var OUTSIDE: Int32
}
