// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("org.bukkit.event.inventory.InventoryClickEvent")
open class InventoryClickEvent: JavaObject {
  /// Java method `setCursor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void org.bukkit.event.inventory.InventoryClickEvent.setCursor(org.bukkit.inventory.ItemStack)
  /// ```
@available(*, deprecated)
  @JavaMethod
  open func setCursor(_ arg0: ItemStack?)

  /// Java method `getCursor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public org.bukkit.inventory.ItemStack org.bukkit.event.inventory.InventoryClickEvent.getCursor()
  /// ```
@JavaMethod
  open func getCursor() -> ItemStack!

  /// Java method `isRightClick`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean org.bukkit.event.inventory.InventoryClickEvent.isRightClick()
  /// ```
@JavaMethod
  open func isRightClick() -> Bool

  /// Java method `isLeftClick`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean org.bukkit.event.inventory.InventoryClickEvent.isLeftClick()
  /// ```
@JavaMethod
  open func isLeftClick() -> Bool

  /// Java method `isShiftClick`.
  ///
  /// ### Java method signature
  /// ```java
  /// public boolean org.bukkit.event.inventory.InventoryClickEvent.isShiftClick()
  /// ```
@JavaMethod
  open func isShiftClick() -> Bool

  /// Java method `getCurrentItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public org.bukkit.inventory.ItemStack org.bukkit.event.inventory.InventoryClickEvent.getCurrentItem()
  /// ```
@JavaMethod
  open func getCurrentItem() -> ItemStack!

  /// Java method `setCurrentItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public void org.bukkit.event.inventory.InventoryClickEvent.setCurrentItem(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  open func setCurrentItem(_ arg0: ItemStack?)

  /// Java method `getRawSlot`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int org.bukkit.event.inventory.InventoryClickEvent.getRawSlot()
  /// ```
@JavaMethod
  open func getRawSlot() -> Int32

  /// Java method `getHotbarButton`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int org.bukkit.event.inventory.InventoryClickEvent.getHotbarButton()
  /// ```
@JavaMethod
  open func getHotbarButton() -> Int32

  /// Java method `getClickedInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public org.bukkit.inventory.Inventory org.bukkit.event.inventory.InventoryClickEvent.getClickedInventory()
  /// ```
@JavaMethod
  open func getClickedInventory() -> Inventory!

  /// Java method `getSlot`.
  ///
  /// ### Java method signature
  /// ```java
  /// public int org.bukkit.event.inventory.InventoryClickEvent.getSlot()
  /// ```
@JavaMethod
  open func getSlot() -> Int32
}
