// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("org.bukkit.inventory.meta.ItemMeta")
public struct ItemMeta {
  /// Java method `clone`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.meta.ItemMeta org.bukkit.inventory.meta.ItemMeta.clone()
  /// ```
@JavaMethod
  public func clone() -> ItemMeta!

  /// Java method `setVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setVersion(int)
  /// ```
@JavaMethod
  public func setVersion(_ arg0: Int32)

  /// Java method `getDisplayName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.meta.ItemMeta.getDisplayName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getDisplayName() -> String

  /// Java method `getLocalizedName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.meta.ItemMeta.getLocalizedName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getLocalizedName() -> String

  /// Java method `getMaxStackSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.meta.ItemMeta.getMaxStackSize()
  /// ```
@JavaMethod
  public func getMaxStackSize() -> Int32

  /// Java method `hasItemName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasItemName()
  /// ```
@JavaMethod
  public func hasItemName() -> Bool

  /// Java method `hasDisplayName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean org.bukkit.inventory.meta.ItemMeta.hasDisplayName()
  /// ```
@JavaMethod
  public func hasDisplayName() -> Bool

  /// Java method `hasCustomName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasCustomName()
  /// ```
@JavaMethod
  public func hasCustomName() -> Bool

  /// Java method `getItemName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.meta.ItemMeta.getItemName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getItemName() -> String

  /// Java method `setItemName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setItemName(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setItemName(_ arg0: String)

  /// Java method `hasLocalizedName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasLocalizedName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func hasLocalizedName() -> Bool

  /// Java method `setLocalizedName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setLocalizedName(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setLocalizedName(_ arg0: String)

  /// Java method `hasLore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasLore()
  /// ```
@JavaMethod
  public func hasLore() -> Bool

  /// Java method `hasCustomModelData`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasCustomModelData()
  /// ```
@JavaMethod
  public func hasCustomModelData() -> Bool

  /// Java method `getCustomModelData`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.meta.ItemMeta.getCustomModelData()
  /// ```
@JavaMethod
  public func getCustomModelData() -> Int32

  /// Java method `hasEnchantable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasEnchantable()
  /// ```
@JavaMethod
  public func hasEnchantable() -> Bool

  /// Java method `getEnchantable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.inventory.meta.ItemMeta.getEnchantable()
  /// ```
@JavaMethod
  public func getEnchantable() -> Int32

  /// Java method `hasEnchants`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasEnchants()
  /// ```
@JavaMethod
  public func hasEnchants() -> Bool

  /// Java method `removeEnchantments`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.removeEnchantments()
  /// ```
@JavaMethod
  public func removeEnchantments()

  /// Java method `isHideTooltip`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.isHideTooltip()
  /// ```
@JavaMethod
  public func isHideTooltip() -> Bool

  /// Java method `setHideTooltip`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setHideTooltip(boolean)
  /// ```
@JavaMethod
  public func setHideTooltip(_ arg0: Bool)

  /// Java method `hasTooltipStyle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasTooltipStyle()
  /// ```
@JavaMethod
  public func hasTooltipStyle() -> Bool

  /// Java method `hasItemModel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasItemModel()
  /// ```
@JavaMethod
  public func hasItemModel() -> Bool

  /// Java method `isUnbreakable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.isUnbreakable()
  /// ```
@JavaMethod
  public func isUnbreakable() -> Bool

  /// Java method `setUnbreakable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setUnbreakable(boolean)
  /// ```
@JavaMethod
  public func setUnbreakable(_ arg0: Bool)

  /// Java method `isGlider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.isGlider()
  /// ```
@JavaMethod
  public func isGlider() -> Bool

  /// Java method `setGlider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setGlider(boolean)
  /// ```
@JavaMethod
  public func setGlider(_ arg0: Bool)

  /// Java method `isFireResistant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.isFireResistant()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func isFireResistant() -> Bool

  /// Java method `setFireResistant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setFireResistant(boolean)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setFireResistant(_ arg0: Bool)

  /// Java method `hasDamageResistant`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasDamageResistant()
  /// ```
@JavaMethod
  public func hasDamageResistant() -> Bool

  /// Java method `hasMaxStackSize`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasMaxStackSize()
  /// ```
@JavaMethod
  public func hasMaxStackSize() -> Bool

  /// Java method `hasRarity`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasRarity()
  /// ```
@JavaMethod
  public func hasRarity() -> Bool

  /// Java method `hasUseRemainder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasUseRemainder()
  /// ```
@JavaMethod
  public func hasUseRemainder() -> Bool

  /// Java method `getUseRemainder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.inventory.meta.ItemMeta.getUseRemainder()
  /// ```
@JavaMethod
  public func getUseRemainder() -> ItemStack!

  /// Java method `setUseRemainder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setUseRemainder(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func setUseRemainder(_ arg0: ItemStack?)

  /// Java method `hasUseCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasUseCooldown()
  /// ```
@JavaMethod
  public func hasUseCooldown() -> Bool

  /// Java method `hasFood`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasFood()
  /// ```
@JavaMethod
  public func hasFood() -> Bool

  /// Java method `hasTool`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasTool()
  /// ```
@JavaMethod
  public func hasTool() -> Bool

  /// Java method `hasJukeboxPlayable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasJukeboxPlayable()
  /// ```
@JavaMethod
  public func hasJukeboxPlayable() -> Bool

  /// Java method `hasPlaceableKeys`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasPlaceableKeys()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func hasPlaceableKeys() -> Bool

  /// Java method `hasDestroyableKeys`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasDestroyableKeys()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func hasDestroyableKeys() -> Bool

  /// Java method `setDisplayName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.inventory.meta.ItemMeta.setDisplayName(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setDisplayName(_ arg0: String)

  /// Java method `getAsString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.meta.ItemMeta.getAsString()
  /// ```
@JavaMethod
  public func getAsString() -> String

  /// Java method `hasEquippable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasEquippable()
  /// ```
@JavaMethod
  public func hasEquippable() -> Bool

  /// Java method `hasEnchantmentGlintOverride`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasEnchantmentGlintOverride()
  /// ```
@JavaMethod
  public func hasEnchantmentGlintOverride() -> Bool

  /// Java method `hasAttributeModifiers`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.inventory.meta.ItemMeta.hasAttributeModifiers()
  /// ```
@JavaMethod
  public func hasAttributeModifiers() -> Bool

  /// Java method `getAsComponentString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.inventory.meta.ItemMeta.getAsComponentString()
  /// ```
@JavaMethod
  public func getAsComponentString() -> String
}
