// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("com.snj.ItemCreator")
open class ItemCreator: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)
}
extension JavaClass<ItemCreator> {
  /// Java method `sendMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void com.snj.ItemCreator.sendMessage(java.lang.String,java.lang.String)
  /// ```
@JavaStaticMethod
  public func sendMessage(_ arg0: String, _ arg1: String)

  /// Java method `createItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.inventory.ItemStack com.snj.ItemCreator.createItem(java.lang.String,java.lang.String,int)
  /// ```
@JavaStaticMethod
  public func createItem(_ arg0: String, _ arg1: String, _ arg2: Int32) -> ItemStack!

  /// Java method `giveItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static void com.snj.ItemCreator.giveItem(java.lang.String,java.lang.String,java.lang.String,int)
  /// ```
@JavaStaticMethod
  public func giveItem(_ arg0: String, _ arg1: String, _ arg2: String, _ arg3: Int32)
}
