// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaClass("org.bukkit.inventory.ItemStack")
open class ItemStack: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(_ arg0: ItemStack?, environment: JNIEnvironment? = nil) throws

    /// Java method `translationKey`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String org.bukkit.inventory.ItemStack.translationKey()
    /// ```
  @JavaMethod
  open func translationKey() -> String

    /// Java method `getTranslationKey`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String org.bukkit.inventory.ItemStack.getTranslationKey()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getTranslationKey() -> String

    /// Java method `setDurability`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setDurability(short)
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func setDurability(_ arg0: Int16)

    /// Java method `setAmount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setAmount(int)
    /// ```
  @JavaMethod
  open func setAmount(_ arg0: Int32)

    /// Java method `getDurability`.
    ///
    /// ### Java method signature
    /// ```java
    /// public short org.bukkit.inventory.ItemStack.getDurability()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getDurability() -> Int16

    /// Java method `hasItemMeta`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasItemMeta()
    /// ```
  @JavaMethod
  open func hasItemMeta() -> Bool

    /// Java method `isSimilar`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.isSimilar(org.bukkit.inventory.ItemStack)
    /// ```
  @JavaMethod
  open func isSimilar(_ arg0: ItemStack?) -> Bool

    /// Java method `serializeAsBytes`.
    ///
    /// ### Java method signature
    /// ```java
    /// public byte[] org.bukkit.inventory.ItemStack.serializeAsBytes()
    /// ```
  @JavaMethod
  open func serializeAsBytes() -> [Int8]

    /// Java method `getI18NDisplayName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String org.bukkit.inventory.ItemStack.getI18NDisplayName()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getI18NDisplayName() -> String

    /// Java method `asQuantity`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.asQuantity(int)
    /// ```
  @JavaMethod
  open func asQuantity(_ arg0: Int32) -> ItemStack!

    /// Java method `hasBlockData`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasBlockData()
    /// ```
  @JavaMethod
  open func hasBlockData() -> Bool

    /// Java method `getRepairCost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.getRepairCost()
    /// ```
  @JavaMethod
  open func getRepairCost() -> Int32

    /// Java method `setRepairCost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setRepairCost(int)
    /// ```
  @JavaMethod
  open func setRepairCost(_ arg0: Int32)

    /// Java method `hasRepairCost`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasRepairCost()
    /// ```
  @JavaMethod
  open func hasRepairCost() -> Bool

    /// Java method `hasDamage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasDamage()
    /// ```
  @JavaMethod
  open func hasDamage() -> Bool

    /// Java method `getDamage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.getDamage()
    /// ```
  @JavaMethod
  open func getDamage() -> Int32

    /// Java method `setDamage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setDamage(int)
    /// ```
  @JavaMethod
  open func setDamage(_ arg0: Int32)

    /// Java method `repair`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.repair()
    /// ```
  @JavaMethod
  open func repair()

    /// Java method `repair`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.repair(int)
    /// ```
  @JavaMethod
  open func repair(_ arg0: Int32)

    /// Java method `asOne`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.asOne()
    /// ```
  @JavaMethod
  open func asOne() -> ItemStack!

    /// Java method `isRepairableBy`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.isRepairableBy(org.bukkit.inventory.ItemStack)
    /// ```
  @JavaMethod
  open func isRepairableBy(_ arg0: ItemStack?) -> Bool

    /// Java method `canRepair`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.canRepair(org.bukkit.inventory.ItemStack)
    /// ```
  @JavaMethod
  open func canRepair(_ arg0: ItemStack?) -> Bool

    /// Java method `hasDisplayName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasDisplayName()
    /// ```
  @JavaMethod
  open func hasDisplayName() -> Bool

    /// Java method `hasLocalizedName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasLocalizedName()
    /// ```
  @JavaMethod
  open func hasLocalizedName() -> Bool

    /// Java method `setLocalizedName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setLocalizedName(java.lang.String)
    /// ```
  @JavaMethod
  open func setLocalizedName(_ arg0: String)

    /// Java method `hasLore`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasLore()
    /// ```
  @JavaMethod
  open func hasLore() -> Bool

    /// Java method `hasCustomModelData`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasCustomModelData()
    /// ```
  @JavaMethod
  open func hasCustomModelData() -> Bool

    /// Java method `getCustomModelData`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.getCustomModelData()
    /// ```
  @JavaMethod
  open func getCustomModelData() -> Int32

    /// Java method `hasEnchants`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasEnchants()
    /// ```
  @JavaMethod
  open func hasEnchants() -> Bool

    /// Java method `removeEnchantments`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.removeEnchantments()
    /// ```
  @JavaMethod
  open func removeEnchantments()

    /// Java method `isUnbreakable`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.isUnbreakable()
    /// ```
  @JavaMethod
  open func isUnbreakable() -> Bool

    /// Java method `setUnbreakable`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setUnbreakable(boolean)
    /// ```
  @JavaMethod
  open func setUnbreakable(_ arg0: Bool)

    /// Java method `getItemMeta`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.meta.ItemMeta org.bukkit.inventory.ItemStack.getItemMeta()
    /// ```
  @JavaMethod
  open func getItemMeta() -> ItemMeta!

    /// Java method `setDisplayName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.inventory.ItemStack.setDisplayName(java.lang.String)
    /// ```
  @JavaMethod
  open func setDisplayName(_ arg0: String)

    /// Java method `setItemMeta`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.setItemMeta(org.bukkit.inventory.meta.ItemMeta)
    /// ```
  @JavaMethod
  open func setItemMeta(_ arg0: ItemMeta?) -> Bool

    /// Java method `getMaxStackSize`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.getMaxStackSize()
    /// ```
  @JavaMethod
  open func getMaxStackSize() -> Int32

    /// Java method `getAmount`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.getAmount()
    /// ```
  @JavaMethod
  open func getAmount() -> Int32

    /// Java method `damage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.damage(int,boolean)
    /// ```
  @JavaMethod
  open func damage(_ arg0: Int32, _ arg1: Bool) -> Bool

    /// Java method `damage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.damage()
    /// ```
  @JavaMethod
  open func damage() -> Bool

    /// Java method `damage`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.damage(int)
    /// ```
  @JavaMethod
  open func damage(_ arg0: Int32) -> Bool

    /// Java method `ensureServerConversions`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.ensureServerConversions()
    /// ```
  @JavaMethod
  open func ensureServerConversions() -> ItemStack!

    /// Java method `getMaxItemUseDuration`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.getMaxItemUseDuration()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getMaxItemUseDuration() -> Int32

    /// Java method `hasAttributeModifiers`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.hasAttributeModifiers()
    /// ```
  @JavaMethod
  open func hasAttributeModifiers() -> Bool

    /// Java method `equals`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.equals(java.lang.Object)
    /// ```
  @JavaMethod
  open override func equals(_ arg0: JavaObject?) -> Bool

    /// Java method `toString`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String org.bukkit.inventory.ItemStack.toString()
    /// ```
  @JavaMethod
  open override func toString() -> String

    /// Java method `hashCode`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.inventory.ItemStack.hashCode()
    /// ```
  @JavaMethod
  open override func hashCode() -> Int32

    /// Java method `clone`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.clone()
    /// ```
  @JavaMethod
  open override func clone() -> ItemStack!

    /// Java method `isEmpty`.
    ///
    /// ### Java method signature
    /// ```java
    /// public boolean org.bukkit.inventory.ItemStack.isEmpty()
    /// ```
  @JavaMethod
  open func isEmpty() -> Bool

    /// Java method `add`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.add()
    /// ```
  @JavaMethod
  open func add() -> ItemStack!

    /// Java method `add`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.add(int)
    /// ```
  @JavaMethod
  open func add(_ arg0: Int32) -> ItemStack!

    /// Java method `subtract`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.subtract(int)
    /// ```
  @JavaMethod
  open func subtract(_ arg0: Int32) -> ItemStack!

    /// Java method `subtract`.
    ///
    /// ### Java method signature
    /// ```java
    /// public org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.subtract()
    /// ```
  @JavaMethod
  open func subtract() -> ItemStack!

    /// Java method `getDisplayName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String org.bukkit.inventory.ItemStack.getDisplayName()
    /// ```
  @JavaMethod
  open func getDisplayName() -> String

    /// Java method `getLocalizedName`.
    ///
    /// ### Java method signature
    /// ```java
    /// public java.lang.String org.bukkit.inventory.ItemStack.getLocalizedName()
    /// ```
  @JavaMethod
  open func getLocalizedName() -> String
}
extension JavaClass<ItemStack> {
  /// Java method `deserializeBytes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.deserializeBytes(byte[])
  /// ```
@JavaStaticMethod
  public func deserializeBytes(_ arg0: [Int8]) -> ItemStack!

  /// Java method `serializeItemsAsBytes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static byte[] org.bukkit.inventory.ItemStack.serializeItemsAsBytes(org.bukkit.inventory.ItemStack[])
  /// ```
@JavaStaticMethod
  public func serializeItemsAsBytes(_ arg0: [ItemStack?]) -> [Int8]

  /// Java method `deserializeItemsFromBytes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.inventory.ItemStack[] org.bukkit.inventory.ItemStack.deserializeItemsFromBytes(byte[])
  /// ```
@JavaStaticMethod
  public func deserializeItemsFromBytes(_ arg0: [Int8]) -> [ItemStack?]

  /// Java method `empty`.
  ///
  /// ### Java method signature
  /// ```java
  /// public static org.bukkit.inventory.ItemStack org.bukkit.inventory.ItemStack.empty()
  /// ```
@JavaStaticMethod
  public func empty() -> ItemStack!
}
