// Auto-generated by Java-to-Swift wrapper generator.
import SwiftJava
import SwiftJavaJNICore

@JavaInterface("org.bukkit.entity.Player")
public struct Player {
  /// Java method `stopSound`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.stopSound(java.lang.String)
  /// ```
@JavaMethod
  public func stopSound(_ arg0: String)

  /// Java method `stopAllSounds`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.stopAllSounds()
  /// ```
@JavaMethod
  public func stopAllSounds()

  /// Java method `showWinScreen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.showWinScreen()
  /// ```
@JavaMethod
  public func showWinScreen()

  /// Java method `hasSeenWinScreen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.hasSeenWinScreen()
  /// ```
@JavaMethod
  public func hasSeenWinScreen() -> Bool

  /// Java method `sendActionBar`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendActionBar(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func sendActionBar(_ arg0: String)

  /// Java method `sendActionBar`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendActionBar(char,java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func sendActionBar(_ arg0: UInt16, _ arg1: String)

  /// Java method `setTitleTimes`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setTitleTimes(int,int,int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setTitleTimes(_ arg0: Int32, _ arg1: Int32, _ arg2: Int32)

  /// Java method `sendTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendTitle(java.lang.String,java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func sendTitle(_ arg0: String, _ arg1: String)

  /// Java method `sendTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendTitle(java.lang.String,java.lang.String,int,int,int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func sendTitle(_ arg0: String, _ arg1: String, _ arg2: Int32, _ arg3: Int32, _ arg4: Int32)

  /// Java method `hideTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.hideTitle()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func hideTitle()

  /// Java method `sendHurtAnimation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendHurtAnimation(float)
  /// ```
@JavaMethod
  public func sendHurtAnimation(_ arg0: Float)

  /// Java method `updateInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.updateInventory()
  /// ```
@JavaMethod
  public func updateInventory()

  /// Java method `setPlayerTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setPlayerTime(long,boolean)
  /// ```
@JavaMethod
  public func setPlayerTime(_ arg0: Int64, _ arg1: Bool)

  /// Java method `getPlayerTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long org.bukkit.entity.Player.getPlayerTime()
  /// ```
@JavaMethod
  public func getPlayerTime() -> Int64

  /// Java method `resetPlayerTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.resetPlayerTime()
  /// ```
@JavaMethod
  public func resetPlayerTime()

  /// Java method `resetPlayerWeather`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.resetPlayerWeather()
  /// ```
@JavaMethod
  public func resetPlayerWeather()

  /// Java method `getExpCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getExpCooldown()
  /// ```
@JavaMethod
  public func getExpCooldown() -> Int32

  /// Java method `setExpCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setExpCooldown(int)
  /// ```
@JavaMethod
  public func setExpCooldown(_ arg0: Int32)

  /// Java method `applyMending`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.applyMending(int)
  /// ```
@JavaMethod
  public func applyMending(_ arg0: Int32) -> Int32

  /// Java method `giveExpLevels`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.giveExpLevels(int)
  /// ```
@JavaMethod
  public func giveExpLevels(_ arg0: Int32)

  /// Java method `getExp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Player.getExp()
  /// ```
@JavaMethod
  public func getExp() -> Float

  /// Java method `setExp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setExp(float)
  /// ```
@JavaMethod
  public func setExp(_ arg0: Float)

  /// Java method `getTotalExperience`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getTotalExperience()
  /// ```
@JavaMethod
  public func getTotalExperience() -> Int32

  /// Java method `setTotalExperience`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setTotalExperience(int)
  /// ```
@JavaMethod
  public func setTotalExperience(_ arg0: Int32)

  /// Java method `setAllowFlight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setAllowFlight(boolean)
  /// ```
@JavaMethod
  public func setAllowFlight(_ arg0: Bool)

  /// Java method `hidePlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.hidePlayer(org.bukkit.entity.Player)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func hidePlayer(_ arg0: Player?)

  /// Java method `showPlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.showPlayer(org.bukkit.entity.Player)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func showPlayer(_ arg0: Player?)

  /// Java method `canSee`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.canSee(org.bukkit.entity.Player)
  /// ```
@JavaMethod
  public func canSee(_ arg0: Player?) -> Bool

  /// Java method `isListed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isListed(org.bukkit.entity.Player)
  /// ```
@JavaMethod
  public func isListed(_ arg0: Player?) -> Bool

  /// Java method `unlistPlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.unlistPlayer(org.bukkit.entity.Player)
  /// ```
@JavaMethod
  public func unlistPlayer(_ arg0: Player?) -> Bool

  /// Java method `listPlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.listPlayer(org.bukkit.entity.Player)
  /// ```
@JavaMethod
  public func listPlayer(_ arg0: Player?) -> Bool

  /// Java method `isFlying`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isFlying()
  /// ```
@JavaMethod
  public func isFlying() -> Bool

  /// Java method `setFlying`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setFlying(boolean)
  /// ```
@JavaMethod
  public func setFlying(_ arg0: Bool)

  /// Java method `setFlySpeed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setFlySpeed(float) throws java.lang.IllegalArgumentException
  /// ```
@JavaMethod
  public func setFlySpeed(_ arg0: Float) throws

  /// Java method `setWalkSpeed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setWalkSpeed(float) throws java.lang.IllegalArgumentException
  /// ```
@JavaMethod
  public func setWalkSpeed(_ arg0: Float) throws

  /// Java method `getFlySpeed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Player.getFlySpeed()
  /// ```
@JavaMethod
  public func getFlySpeed() -> Float

  /// Java method `getWalkSpeed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Player.getWalkSpeed()
  /// ```
@JavaMethod
  public func getWalkSpeed() -> Float

  /// Java method `setTexturePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setTexturePack(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setTexturePack(_ arg0: String)

  /// Java method `hasResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default boolean org.bukkit.entity.Player.hasResourcePack()
  /// ```
@JavaMethod
  public func hasResourcePack() -> Bool

  /// Java method `sendHealthUpdate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendHealthUpdate(double,int,float)
  /// ```
@JavaMethod
  public func sendHealthUpdate(_ arg0: Double, _ arg1: Int32, _ arg2: Float)

  /// Java method `sendHealthUpdate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendHealthUpdate()
  /// ```
@JavaMethod
  public func sendHealthUpdate()

  /// Java method `isHealthScaled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isHealthScaled()
  /// ```
@JavaMethod
  public func isHealthScaled() -> Bool

  /// Java method `setHealthScaled`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setHealthScaled(boolean)
  /// ```
@JavaMethod
  public func setHealthScaled(_ arg0: Bool)

  /// Java method `setHealthScale`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setHealthScale(double) throws java.lang.IllegalArgumentException
  /// ```
@JavaMethod
  public func setHealthScale(_ arg0: Double) throws

  /// Java method `getHealthScale`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Player.getHealthScale()
  /// ```
@JavaMethod
  public func getHealthScale() -> Double

  /// Java method `resetTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.resetTitle()
  /// ```
@JavaMethod
  public func resetTitle()

  /// Java method `getPing`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getPing()
  /// ```
@JavaMethod
  public func getPing() -> Int32

  /// Java method `getAffectsSpawning`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.getAffectsSpawning()
  /// ```
@JavaMethod
  public func getAffectsSpawning() -> Bool

  /// Java method `setAffectsSpawning`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setAffectsSpawning(boolean)
  /// ```
@JavaMethod
  public func setAffectsSpawning(_ arg0: Bool)

  /// Java method `updateCommands`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.updateCommands()
  /// ```
@JavaMethod
  public func updateCommands()

  /// Java method `openBook`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.openBook(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func openBook(_ arg0: ItemStack?)

  /// Java method `showDemoScreen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.showDemoScreen()
  /// ```
@JavaMethod
  public func showDemoScreen()

  /// Java method `getCooldownPeriod`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Player.getCooldownPeriod()
  /// ```
@JavaMethod
  public func getCooldownPeriod() -> Float

  /// Java method `resetCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.resetCooldown()
  /// ```
@JavaMethod
  public func resetCooldown()

  /// Java method `sendOpLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendOpLevel(byte)
  /// ```
@JavaMethod
  public func sendOpLevel(_ arg0: Int8)

  /// Java method `getClientBrandName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getClientBrandName()
  /// ```
@JavaMethod
  public func getClientBrandName() -> String

  /// Java method `setRotation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setRotation(float,float)
  /// ```
@JavaMethod
  public func setRotation(_ arg0: Float, _ arg1: Float)

  /// Java method `resetIdleDuration`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.resetIdleDuration()
  /// ```
@JavaMethod
  public func resetIdleDuration()

  /// Java method `usesPurpurClient`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.usesPurpurClient()
  /// ```
@JavaMethod
  public func usesPurpurClient() -> Bool

  /// Java method `isAfk`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isAfk()
  /// ```
@JavaMethod
  public func isAfk() -> Bool

  /// Java method `setAfk`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setAfk(boolean)
  /// ```
@JavaMethod
  public func setAfk(_ arg0: Bool)

  /// Java method `resetIdleTimer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.resetIdleTimer()
  /// ```
@JavaMethod
  public func resetIdleTimer()

  /// Java method `getViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getViewDistance()
  /// ```
@JavaMethod
  public func getViewDistance() -> Int32

  /// Java method `getAllowFlight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.getAllowFlight()
  /// ```
@JavaMethod
  public func getAllowFlight() -> Bool

  /// Java method `spigot`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.entity.Player$Spigot org.bukkit.entity.Player.spigot()
  /// ```
@JavaMethod
  public func spigot() -> Player.Spigot!

  /// Java method `setDisplayName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setDisplayName(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setDisplayName(_ arg0: String)

  /// Java method `kickPlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.kickPlayer(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func kickPlayer(_ arg0: String)

  /// Java method `giveExp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.Player.giveExp(int)
  /// ```
@JavaMethod
  public func giveExp(_ arg0: Int32)

  /// Java method `giveExp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.giveExp(int,boolean)
  /// ```
@JavaMethod
  public func giveExp(_ arg0: Int32, _ arg1: Bool)

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setResourcePack(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setResourcePack(_ arg0: String)

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.Player.setResourcePack(java.lang.String,java.lang.String,boolean)
  /// ```
@JavaMethod
  public func setResourcePack(_ arg0: String, _ arg1: String, _ arg2: Bool)

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setResourcePack(java.lang.String,byte[],java.lang.String,boolean)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setResourcePack(_ arg0: String, _ arg1: [Int8], _ arg2: String, _ arg3: Bool)

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setResourcePack(java.lang.String,byte[],java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setResourcePack(_ arg0: String, _ arg1: [Int8], _ arg2: String)

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setResourcePack(java.lang.String,byte[])
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setResourcePack(_ arg0: String, _ arg1: [Int8])

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.Player.setResourcePack(java.lang.String,java.lang.String)
  /// ```
@JavaMethod
  public func setResourcePack(_ arg0: String, _ arg1: String)

  /// Java method `setResourcePack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setResourcePack(java.lang.String,byte[],boolean)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setResourcePack(_ arg0: String, _ arg1: [Int8], _ arg2: Bool)

  /// Java method `setViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setViewDistance(int)
  /// ```
@JavaMethod
  public func setViewDistance(_ arg0: Int32)

  /// Java method `showElderGuardian`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.Player.showElderGuardian()
  /// ```
@JavaMethod
  public func showElderGuardian()

  /// Java method `showElderGuardian`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.showElderGuardian(boolean)
  /// ```
@JavaMethod
  public func showElderGuardian(_ arg0: Bool)

  /// Java method `isChunkSent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isChunkSent(long)
  /// ```
@JavaMethod
  public func isChunkSent(_ arg0: Int64) -> Bool

  /// Java method `getPlayerListName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getPlayerListName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getPlayerListName() -> String

  /// Java method `setPlayerListName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setPlayerListName(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setPlayerListName(_ arg0: String)

  /// Java method `getPlayerListOrder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getPlayerListOrder()
  /// ```
@JavaMethod
  public func getPlayerListOrder() -> Int32

  /// Java method `setPlayerListOrder`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setPlayerListOrder(int)
  /// ```
@JavaMethod
  public func setPlayerListOrder(_ arg0: Int32)

  /// Java method `isTransferred`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isTransferred()
  /// ```
@JavaMethod
  public func isTransferred() -> Bool

  /// Java method `sendRawMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendRawMessage(java.lang.String)
  /// ```
@JavaMethod
  public func sendRawMessage(_ arg0: String)

  /// Java method `kick`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.kick()
  /// ```
@JavaMethod
  public func kick()

  /// Java method `chat`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.chat(java.lang.String)
  /// ```
@JavaMethod
  public func chat(_ arg0: String)

  /// Java method `performCommand`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.performCommand(java.lang.String)
  /// ```
@JavaMethod
  public func performCommand(_ arg0: String) -> Bool

  /// Java method `isOnGround`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isOnGround()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func isOnGround() -> Bool

  /// Java method `isSneaking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isSneaking()
  /// ```
@JavaMethod
  public func isSneaking() -> Bool

  /// Java method `setSneaking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setSneaking(boolean)
  /// ```
@JavaMethod
  public func setSneaking(_ arg0: Bool)

  /// Java method `isSprinting`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isSprinting()
  /// ```
@JavaMethod
  public func isSprinting() -> Bool

  /// Java method `setSprinting`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setSprinting(boolean)
  /// ```
@JavaMethod
  public func setSprinting(_ arg0: Bool)

  /// Java method `saveData`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.saveData()
  /// ```
@JavaMethod
  public func saveData()

  /// Java method `loadData`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.loadData()
  /// ```
@JavaMethod
  public func loadData()

  /// Java method `setSleepingIgnored`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setSleepingIgnored(boolean)
  /// ```
@JavaMethod
  public func setSleepingIgnored(_ arg0: Bool)

  /// Java method `isSleepingIgnored`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isSleepingIgnored()
  /// ```
@JavaMethod
  public func isSleepingIgnored() -> Bool

  /// Java method `getSimulationDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getSimulationDistance()
  /// ```
@JavaMethod
  public func getSimulationDistance() -> Int32

  /// Java method `getResourcePackHash`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default java.lang.String org.bukkit.entity.Player.getResourcePackHash()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getResourcePackHash() -> String

  /// Java method `clearBlockHighlights`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.clearBlockHighlights()
  /// ```
@JavaMethod
  public func clearBlockHighlights()

  /// Java method `getPlayerListHeader`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getPlayerListHeader()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getPlayerListHeader() -> String

  /// Java method `getPlayerListFooter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getPlayerListFooter()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getPlayerListFooter() -> String

  /// Java method `setPlayerListHeader`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setPlayerListHeader(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setPlayerListHeader(_ arg0: String)

  /// Java method `setPlayerListFooter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setPlayerListFooter(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setPlayerListFooter(_ arg0: String)

  /// Java method `setPlayerListHeaderFooter`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setPlayerListHeaderFooter(java.lang.String,java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setPlayerListHeaderFooter(_ arg0: String, _ arg1: String)

  /// Java method `setHasSeenWinScreen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setHasSeenWinScreen(boolean)
  /// ```
@JavaMethod
  public func setHasSeenWinScreen(_ arg0: Bool)

  /// Java method `getPlayerTimeOffset`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long org.bukkit.entity.Player.getPlayerTimeOffset()
  /// ```
@JavaMethod
  public func getPlayerTimeOffset() -> Int64

  /// Java method `isPlayerTimeRelative`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isPlayerTimeRelative()
  /// ```
@JavaMethod
  public func isPlayerTimeRelative() -> Bool

  /// Java method `calculateTotalExperiencePoints`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.calculateTotalExperiencePoints()
  /// ```
@JavaMethod
  public func calculateTotalExperiencePoints() -> Int32

  /// Java method `setExperienceLevelAndProgress`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setExperienceLevelAndProgress(int)
  /// ```
@JavaMethod
  public func setExperienceLevelAndProgress(_ arg0: Int32)

  /// Java method `sendExperienceChange`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendExperienceChange(float,int)
  /// ```
@JavaMethod
  public func sendExperienceChange(_ arg0: Float, _ arg1: Int32)

  /// Java method `sendExperienceChange`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.sendExperienceChange(float)
  /// ```
@JavaMethod
  public func sendExperienceChange(_ arg0: Float)

  /// Java method `removeResourcePacks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.removeResourcePacks()
  /// ```
@JavaMethod
  public func removeResourcePacks()

  /// Java method `getClientViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getClientViewDistance()
  /// ```
@JavaMethod
  public func getClientViewDistance() -> Int32

  /// Java method `setSimulationDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setSimulationDistance(int)
  /// ```
@JavaMethod
  public func setSimulationDistance(_ arg0: Int32)

  /// Java method `getNoTickViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int org.bukkit.entity.Player.getNoTickViewDistance()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getNoTickViewDistance() -> Int32

  /// Java method `setNoTickViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.Player.setNoTickViewDistance(int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setNoTickViewDistance(_ arg0: Int32)

  /// Java method `getSendViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getSendViewDistance()
  /// ```
@JavaMethod
  public func getSendViewDistance() -> Int32

  /// Java method `setSendViewDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setSendViewDistance(int)
  /// ```
@JavaMethod
  public func setSendViewDistance(_ arg0: Int32)

  /// Java method `isAllowingServerListings`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Player.isAllowingServerListings()
  /// ```
@JavaMethod
  public func isAllowingServerListings() -> Bool

  /// Java method `getCooledAttackStrength`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Player.getCooledAttackStrength(float)
  /// ```
@JavaMethod
  public func getCooledAttackStrength(_ arg0: Float) -> Float

  /// Java method `getWardenWarningCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getWardenWarningCooldown()
  /// ```
@JavaMethod
  public func getWardenWarningCooldown() -> Int32

  /// Java method `setWardenWarningCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setWardenWarningCooldown(int)
  /// ```
@JavaMethod
  public func setWardenWarningCooldown(_ arg0: Int32)

  /// Java method `getWardenTimeSinceLastWarning`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getWardenTimeSinceLastWarning()
  /// ```
@JavaMethod
  public func getWardenTimeSinceLastWarning() -> Int32

  /// Java method `setWardenTimeSinceLastWarning`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setWardenTimeSinceLastWarning(int)
  /// ```
@JavaMethod
  public func setWardenTimeSinceLastWarning(_ arg0: Int32)

  /// Java method `getWardenWarningLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getWardenWarningLevel()
  /// ```
@JavaMethod
  public func getWardenWarningLevel() -> Int32

  /// Java method `setWardenWarningLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setWardenWarningLevel(int)
  /// ```
@JavaMethod
  public func setWardenWarningLevel(_ arg0: Int32)

  /// Java method `increaseWardenWarningLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.increaseWardenWarningLevel()
  /// ```
@JavaMethod
  public func increaseWardenWarningLevel()

  /// Java method `getDeathScreenScore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getDeathScreenScore()
  /// ```
@JavaMethod
  public func getDeathScreenScore() -> Int32

  /// Java method `setDeathScreenScore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setDeathScreenScore(int)
  /// ```
@JavaMethod
  public func setDeathScreenScore(_ arg0: Int32)

  /// Java method `getExperiencePointsNeededForNextLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getExperiencePointsNeededForNextLevel()
  /// ```
@JavaMethod
  public func getExperiencePointsNeededForNextLevel() -> Int32

  /// Java method `getName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getName()
  /// ```
@JavaMethod
  public func getName() -> String

  /// Java method `transfer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.transfer(java.lang.String,int)
  /// ```
@JavaMethod
  public func transfer(_ arg0: String, _ arg1: Int32)

  /// Java method `getDisplayName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getDisplayName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getDisplayName() -> String

  /// Java method `getLocale`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Player.getLocale()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getLocale() -> String

  /// Java method `setLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Player.setLevel(int)
  /// ```
@JavaMethod
  public func setLevel(_ arg0: Int32)

  /// Java method `getLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Player.getLevel()
  /// ```
@JavaMethod
  public func getLevel() -> Int32

  /// Java method `dropItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.HumanEntity.dropItem(boolean)
  /// ```
@JavaMethod
  public func dropItem(_ arg0: Bool) -> Bool

  /// Java method `getEnderChest`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.Inventory org.bukkit.entity.HumanEntity.getEnderChest()
  /// ```
@JavaMethod
  public func getEnderChest() -> Inventory!

  /// Java method `getEnchantmentSeed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getEnchantmentSeed()
  /// ```
@JavaMethod
  public func getEnchantmentSeed() -> Int32

  /// Java method `setEnchantmentSeed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setEnchantmentSeed(int)
  /// ```
@JavaMethod
  public func setEnchantmentSeed(_ arg0: Int32)

  /// Java method `getOpenInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.InventoryView org.bukkit.entity.HumanEntity.getOpenInventory()
  /// ```
@JavaMethod
  public func getOpenInventory() -> InventoryView!

  /// Java method `openInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.InventoryView org.bukkit.entity.HumanEntity.openInventory(org.bukkit.inventory.Inventory)
  /// ```
@JavaMethod
  public func openInventory(_ arg0: Inventory?) -> InventoryView!

  /// Java method `openInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.openInventory(org.bukkit.inventory.InventoryView)
  /// ```
@JavaMethod
  public func openInventory(_ arg0: InventoryView?)

  /// Java method `closeInventory`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.closeInventory()
  /// ```
@JavaMethod
  public func closeInventory()

  /// Java method `getItemInHand`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.entity.HumanEntity.getItemInHand()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getItemInHand() -> ItemStack!

  /// Java method `setItemInHand`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setItemInHand(org.bukkit.inventory.ItemStack)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setItemInHand(_ arg0: ItemStack?)

  /// Java method `getItemOnCursor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.entity.HumanEntity.getItemOnCursor()
  /// ```
@JavaMethod
  public func getItemOnCursor() -> ItemStack!

  /// Java method `setItemOnCursor`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setItemOnCursor(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func setItemOnCursor(_ arg0: ItemStack?)

  /// Java method `hasCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.HumanEntity.hasCooldown(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func hasCooldown(_ arg0: ItemStack?) -> Bool

  /// Java method `getCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getCooldown(org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func getCooldown(_ arg0: ItemStack?) -> Int32

  /// Java method `setCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setCooldown(org.bukkit.inventory.ItemStack,int)
  /// ```
@JavaMethod
  public func setCooldown(_ arg0: ItemStack?, _ arg1: Int32)

  /// Java method `setHurtDirection`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setHurtDirection(float)
  /// ```
@JavaMethod
  public func setHurtDirection(_ arg0: Float)

  /// Java method `isDeeplySleeping`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.HumanEntity.isDeeplySleeping()
  /// ```
@JavaMethod
  public func isDeeplySleeping() -> Bool

  /// Java method `getSleepTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getSleepTicks()
  /// ```
@JavaMethod
  public func getSleepTicks() -> Int32

  /// Java method `wakeup`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.wakeup(boolean)
  /// ```
@JavaMethod
  public func wakeup(_ arg0: Bool)

  /// Java method `startRiptideAttack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.startRiptideAttack(int,float,org.bukkit.inventory.ItemStack)
  /// ```
@JavaMethod
  public func startRiptideAttack(_ arg0: Int32, _ arg1: Float, _ arg2: ItemStack?)

  /// Java method `isHandRaised`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.HumanEntity.isHandRaised()
  /// ```
@JavaMethod
  public func isHandRaised() -> Bool

  /// Java method `getExpToLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getExpToLevel()
  /// ```
@JavaMethod
  public func getExpToLevel() -> Int32

  /// Java method `getAttackCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.HumanEntity.getAttackCooldown()
  /// ```
@JavaMethod
  public func getAttackCooldown() -> Float

  /// Java method `getExhaustion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.HumanEntity.getExhaustion()
  /// ```
@JavaMethod
  public func getExhaustion() -> Float

  /// Java method `setExhaustion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setExhaustion(float)
  /// ```
@JavaMethod
  public func setExhaustion(_ arg0: Float)

  /// Java method `getSaturation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.HumanEntity.getSaturation()
  /// ```
@JavaMethod
  public func getSaturation() -> Float

  /// Java method `setSaturation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setSaturation(float)
  /// ```
@JavaMethod
  public func setSaturation(_ arg0: Float)

  /// Java method `getFoodLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getFoodLevel()
  /// ```
@JavaMethod
  public func getFoodLevel() -> Int32

  /// Java method `setFoodLevel`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setFoodLevel(int)
  /// ```
@JavaMethod
  public func setFoodLevel(_ arg0: Int32)

  /// Java method `getStarvationRate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getStarvationRate()
  /// ```
@JavaMethod
  public func getStarvationRate() -> Int32

  /// Java method `setStarvationRate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setStarvationRate(int)
  /// ```
@JavaMethod
  public func setStarvationRate(_ arg0: Int32)

  /// Java method `getSaturatedRegenRate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getSaturatedRegenRate()
  /// ```
@JavaMethod
  public func getSaturatedRegenRate() -> Int32

  /// Java method `setSaturatedRegenRate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setSaturatedRegenRate(int)
  /// ```
@JavaMethod
  public func setSaturatedRegenRate(_ arg0: Int32)

  /// Java method `getUnsaturatedRegenRate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.HumanEntity.getUnsaturatedRegenRate()
  /// ```
@JavaMethod
  public func getUnsaturatedRegenRate() -> Int32

  /// Java method `setUnsaturatedRegenRate`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.HumanEntity.setUnsaturatedRegenRate(int)
  /// ```
@JavaMethod
  public func setUnsaturatedRegenRate(_ arg0: Int32)

  /// Java method `isBlocking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.HumanEntity.isBlocking()
  /// ```
@JavaMethod
  public func isBlocking() -> Bool

  /// Java method `isGliding`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isGliding()
  /// ```
@JavaMethod
  public func isGliding() -> Bool

  /// Java method `setArrowsInBody`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setArrowsInBody(int,boolean)
  /// ```
@JavaMethod
  public func setArrowsInBody(_ arg0: Int32, _ arg1: Bool)

  /// Java method `setArrowsInBody`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.LivingEntity.setArrowsInBody(int)
  /// ```
@JavaMethod
  public func setArrowsInBody(_ arg0: Int32)

  /// Java method `hasActiveItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.hasActiveItem()
  /// ```
@JavaMethod
  public func hasActiveItem() -> Bool

  /// Java method `swingMainHand`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.swingMainHand()
  /// ```
@JavaMethod
  public func swingMainHand()

  /// Java method `swingOffHand`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.swingOffHand()
  /// ```
@JavaMethod
  public func swingOffHand()

  /// Java method `getEyeHeight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.LivingEntity.getEyeHeight()
  /// ```
@JavaMethod
  public func getEyeHeight() -> Double

  /// Java method `getEyeHeight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.LivingEntity.getEyeHeight(boolean)
  /// ```
@JavaMethod
  public func getEyeHeight(_ arg0: Bool) -> Double

  /// Java method `getRemainingAir`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getRemainingAir()
  /// ```
@JavaMethod
  public func getRemainingAir() -> Int32

  /// Java method `setRemainingAir`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setRemainingAir(int)
  /// ```
@JavaMethod
  public func setRemainingAir(_ arg0: Int32)

  /// Java method `getMaximumAir`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getMaximumAir()
  /// ```
@JavaMethod
  public func getMaximumAir() -> Int32

  /// Java method `setMaximumAir`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setMaximumAir(int)
  /// ```
@JavaMethod
  public func setMaximumAir(_ arg0: Int32)

  /// Java method `getItemInUse`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.entity.LivingEntity.getItemInUse()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getItemInUse() -> ItemStack!

  /// Java method `getItemInUseTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getItemInUseTicks()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getItemInUseTicks() -> Int32

  /// Java method `setItemInUseTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setItemInUseTicks(int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setItemInUseTicks(_ arg0: Int32)

  /// Java method `getArrowCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getArrowCooldown()
  /// ```
@JavaMethod
  public func getArrowCooldown() -> Int32

  /// Java method `setArrowCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setArrowCooldown(int)
  /// ```
@JavaMethod
  public func setArrowCooldown(_ arg0: Int32)

  /// Java method `getArrowsInBody`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getArrowsInBody()
  /// ```
@JavaMethod
  public func getArrowsInBody() -> Int32

  /// Java method `getLastDamage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.LivingEntity.getLastDamage()
  /// ```
@JavaMethod
  public func getLastDamage() -> Double

  /// Java method `setLastDamage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setLastDamage(double)
  /// ```
@JavaMethod
  public func setLastDamage(_ arg0: Double)

  /// Java method `getNoDamageTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getNoDamageTicks()
  /// ```
@JavaMethod
  public func getNoDamageTicks() -> Int32

  /// Java method `setNoDamageTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setNoDamageTicks(int)
  /// ```
@JavaMethod
  public func setNoDamageTicks(_ arg0: Int32)

  /// Java method `getNoActionTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getNoActionTicks()
  /// ```
@JavaMethod
  public func getNoActionTicks() -> Int32

  /// Java method `setNoActionTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setNoActionTicks(int)
  /// ```
@JavaMethod
  public func setNoActionTicks(_ arg0: Int32)

  /// Java method `getKiller`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.entity.Player org.bukkit.entity.LivingEntity.getKiller()
  /// ```
@JavaMethod
  public func getKiller() -> Player!

  /// Java method `setKiller`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setKiller(org.bukkit.entity.Player)
  /// ```
@JavaMethod
  public func setKiller(_ arg0: Player?)

  /// Java method `setCanPickupItems`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setCanPickupItems(boolean)
  /// ```
@JavaMethod
  public func setCanPickupItems(_ arg0: Bool)

  /// Java method `getCanPickupItems`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.getCanPickupItems()
  /// ```
@JavaMethod
  public func getCanPickupItems() -> Bool

  /// Java method `isLeashed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isLeashed()
  /// ```
@JavaMethod
  public func isLeashed() -> Bool

  /// Java method `setGliding`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setGliding(boolean)
  /// ```
@JavaMethod
  public func setGliding(_ arg0: Bool)

  /// Java method `isSwimming`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isSwimming()
  /// ```
@JavaMethod
  public func isSwimming() -> Bool

  /// Java method `setSwimming`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setSwimming(boolean)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setSwimming(_ arg0: Bool)

  /// Java method `isRiptiding`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isRiptiding()
  /// ```
@JavaMethod
  public func isRiptiding() -> Bool

  /// Java method `setRiptiding`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setRiptiding(boolean)
  /// ```
@JavaMethod
  public func setRiptiding(_ arg0: Bool)

  /// Java method `isSleeping`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isSleeping()
  /// ```
@JavaMethod
  public func isSleeping() -> Bool

  /// Java method `isClimbing`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isClimbing()
  /// ```
@JavaMethod
  public func isClimbing() -> Bool

  /// Java method `setAI`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setAI(boolean)
  /// ```
@JavaMethod
  public func setAI(_ arg0: Bool)

  /// Java method `hasAI`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.hasAI()
  /// ```
@JavaMethod
  public func hasAI() -> Bool

  /// Java method `playHurtAnimation`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.playHurtAnimation(float)
  /// ```
@JavaMethod
  public func playHurtAnimation(_ arg0: Float)

  /// Java method `setCollidable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setCollidable(boolean)
  /// ```
@JavaMethod
  public func setCollidable(_ arg0: Bool)

  /// Java method `isCollidable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isCollidable()
  /// ```
@JavaMethod
  public func isCollidable() -> Bool

  /// Java method `setInvisible`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setInvisible(boolean)
  /// ```
@JavaMethod
  public func setInvisible(_ arg0: Bool)

  /// Java method `isInvisible`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isInvisible()
  /// ```
@JavaMethod
  public func isInvisible() -> Bool

  /// Java method `getArrowsStuck`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getArrowsStuck()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getArrowsStuck() -> Int32

  /// Java method `setArrowsStuck`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setArrowsStuck(int)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setArrowsStuck(_ arg0: Int32)

  /// Java method `getUpwardsMovement`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.LivingEntity.getUpwardsMovement()
  /// ```
@JavaMethod
  public func getUpwardsMovement() -> Float

  /// Java method `getActiveItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.entity.LivingEntity.getActiveItem()
  /// ```
@JavaMethod
  public func getActiveItem() -> ItemStack!

  /// Java method `clearActiveItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.clearActiveItem()
  /// ```
@JavaMethod
  public func clearActiveItem()

  /// Java method `getHandRaisedTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int org.bukkit.entity.LivingEntity.getHandRaisedTime()
  /// ```
@JavaMethod
  public func getHandRaisedTime() -> Int32

  /// Java method `isJumping`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.isJumping()
  /// ```
@JavaMethod
  public func isJumping() -> Bool

  /// Java method `setJumping`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setJumping(boolean)
  /// ```
@JavaMethod
  public func setJumping(_ arg0: Bool)

  /// Java method `getHurtDirection`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.LivingEntity.getHurtDirection()
  /// ```
@JavaMethod
  public func getHurtDirection() -> Float

  /// Java method `knockback`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.knockback(double,double,double)
  /// ```
@JavaMethod
  public func knockback(_ arg0: Double, _ arg1: Double, _ arg2: Double)

  /// Java method `damageItemStack`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.inventory.ItemStack org.bukkit.entity.LivingEntity.damageItemStack(org.bukkit.inventory.ItemStack,int)
  /// ```
@JavaMethod
  public func damageItemStack(_ arg0: ItemStack?, _ arg1: Int32) -> ItemStack!

  /// Java method `getBodyYaw`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.LivingEntity.getBodyYaw()
  /// ```
@JavaMethod
  public func getBodyYaw() -> Float

  /// Java method `setBodyYaw`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setBodyYaw(float)
  /// ```
@JavaMethod
  public func setBodyYaw(_ arg0: Float)

  /// Java method `shouldBurnInDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.shouldBurnInDay()
  /// ```
@JavaMethod
  public func shouldBurnInDay() -> Bool

  /// Java method `setShouldBurnInDay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setShouldBurnInDay(boolean)
  /// ```
@JavaMethod
  public func setShouldBurnInDay(_ arg0: Bool)

  /// Java method `getActiveItemRemainingTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getActiveItemRemainingTime()
  /// ```
@JavaMethod
  public func getActiveItemRemainingTime() -> Int32

  /// Java method `getActiveItemUsedTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getActiveItemUsedTime()
  /// ```
@JavaMethod
  public func getActiveItemUsedTime() -> Int32

  /// Java method `setNextArrowRemoval`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setNextArrowRemoval(int)
  /// ```
@JavaMethod
  public func setNextArrowRemoval(_ arg0: Int32)

  /// Java method `getNextArrowRemoval`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getNextArrowRemoval()
  /// ```
@JavaMethod
  public func getNextArrowRemoval() -> Int32

  /// Java method `getBeeStingerCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getBeeStingerCooldown()
  /// ```
@JavaMethod
  public func getBeeStingerCooldown() -> Int32

  /// Java method `setBeeStingerCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setBeeStingerCooldown(int)
  /// ```
@JavaMethod
  public func setBeeStingerCooldown(_ arg0: Int32)

  /// Java method `getBeeStingersInBody`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getBeeStingersInBody()
  /// ```
@JavaMethod
  public func getBeeStingersInBody() -> Int32

  /// Java method `setBeeStingersInBody`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setBeeStingersInBody(int)
  /// ```
@JavaMethod
  public func setBeeStingersInBody(_ arg0: Int32)

  /// Java method `setNextBeeStingerRemoval`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setNextBeeStingerRemoval(int)
  /// ```
@JavaMethod
  public func setNextBeeStingerRemoval(_ arg0: Int32)

  /// Java method `getNextBeeStingerRemoval`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getNextBeeStingerRemoval()
  /// ```
@JavaMethod
  public func getNextBeeStingerRemoval() -> Int32

  /// Java method `getMaximumNoDamageTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getMaximumNoDamageTicks()
  /// ```
@JavaMethod
  public func getMaximumNoDamageTicks() -> Int32

  /// Java method `setMaximumNoDamageTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setMaximumNoDamageTicks(int)
  /// ```
@JavaMethod
  public func setMaximumNoDamageTicks(_ arg0: Int32)

  /// Java method `clearActivePotionEffects`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.clearActivePotionEffects()
  /// ```
@JavaMethod
  public func clearActivePotionEffects() -> Bool

  /// Java method `getRemoveWhenFarAway`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.getRemoveWhenFarAway()
  /// ```
@JavaMethod
  public func getRemoveWhenFarAway() -> Bool

  /// Java method `setRemoveWhenFarAway`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setRemoveWhenFarAway(boolean)
  /// ```
@JavaMethod
  public func setRemoveWhenFarAway(_ arg0: Bool)

  /// Java method `canBreatheUnderwater`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.LivingEntity.canBreatheUnderwater()
  /// ```
@JavaMethod
  public func canBreatheUnderwater() -> Bool

  /// Java method `getShieldBlockingDelay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.LivingEntity.getShieldBlockingDelay()
  /// ```
@JavaMethod
  public func getShieldBlockingDelay() -> Int32

  /// Java method `setShieldBlockingDelay`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setShieldBlockingDelay(int)
  /// ```
@JavaMethod
  public func setShieldBlockingDelay(_ arg0: Int32)

  /// Java method `getSidewaysMovement`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.LivingEntity.getSidewaysMovement()
  /// ```
@JavaMethod
  public func getSidewaysMovement() -> Float

  /// Java method `getForwardsMovement`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.LivingEntity.getForwardsMovement()
  /// ```
@JavaMethod
  public func getForwardsMovement() -> Float

  /// Java method `completeUsingActiveItem`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.completeUsingActiveItem()
  /// ```
@JavaMethod
  public func completeUsingActiveItem()

  /// Java method `setActiveItemRemainingTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.LivingEntity.setActiveItemRemainingTime(int)
  /// ```
@JavaMethod
  public func setActiveItemRemainingTime(_ arg0: Int32)

  /// Java method `getItemUseRemainingTime`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default int org.bukkit.entity.LivingEntity.getItemUseRemainingTime()
  /// ```
@JavaMethod
  public func getItemUseRemainingTime() -> Int32

  /// Java method `heal`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.entity.Damageable.heal(double)
  /// ```
@JavaMethod
  public func heal(_ arg0: Double)

  /// Java method `damage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Damageable.damage(double)
  /// ```
@JavaMethod
  public func damage(_ arg0: Double)

  /// Java method `getHealth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Damageable.getHealth()
  /// ```
@JavaMethod
  public func getHealth() -> Double

  /// Java method `setHealth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Damageable.setHealth(double)
  /// ```
@JavaMethod
  public func setHealth(_ arg0: Double)

  /// Java method `getMaxHealth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Damageable.getMaxHealth()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getMaxHealth() -> Double

  /// Java method `setMaxHealth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Damageable.setMaxHealth(double)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setMaxHealth(_ arg0: Double)

  /// Java method `resetMaxHealth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Damageable.resetMaxHealth()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func resetMaxHealth()

  /// Java method `getAbsorptionAmount`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Damageable.getAbsorptionAmount()
  /// ```
@JavaMethod
  public func getAbsorptionAmount() -> Double

  /// Java method `setAbsorptionAmount`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Damageable.setAbsorptionAmount(double)
  /// ```
@JavaMethod
  public func setAbsorptionAmount(_ arg0: Double)

  /// Java method `getY`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Entity.getY()
  /// ```
@JavaMethod
  public func getY() -> Double

  /// Java method `getZ`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Entity.getZ()
  /// ```
@JavaMethod
  public func getZ() -> Double

  /// Java method `getPitch`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Entity.getPitch()
  /// ```
@JavaMethod
  public func getPitch() -> Float

  /// Java method `getYaw`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Entity.getYaw()
  /// ```
@JavaMethod
  public func getYaw() -> Float

  /// Java method `getRider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.entity.Player org.bukkit.entity.Entity.getRider()
  /// ```
@JavaMethod
  public func getRider() -> Player!

  /// Java method `hasRider`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.hasRider()
  /// ```
@JavaMethod
  public func hasRider() -> Bool

  /// Java method `isRidable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isRidable()
  /// ```
@JavaMethod
  public func isRidable() -> Bool

  /// Java method `isRidableInWater`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isRidableInWater()
  /// ```
@JavaMethod
  public func isRidableInWater() -> Bool

  /// Java method `isInDaylight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInDaylight()
  /// ```
@JavaMethod
  public func isInDaylight() -> Bool

  /// Java method `isImmuneToFire`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isImmuneToFire()
  /// ```
@JavaMethod
  public func isImmuneToFire() -> Bool

  /// Java method `getHeight`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Entity.getHeight()
  /// ```
@JavaMethod
  public func getHeight() -> Double

  /// Java method `getWidth`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Entity.getWidth()
  /// ```
@JavaMethod
  public func getWidth() -> Double

  /// Java method `isInWater`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInWater()
  /// ```
@JavaMethod
  public func isInWater() -> Bool

  /// Java method `getEntityId`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getEntityId()
  /// ```
@JavaMethod
  public func getEntityId() -> Int32

  /// Java method `getFireTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getFireTicks()
  /// ```
@JavaMethod
  public func getFireTicks() -> Int32

  /// Java method `getMaxFireTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getMaxFireTicks()
  /// ```
@JavaMethod
  public func getMaxFireTicks() -> Int32

  /// Java method `setFireTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setFireTicks(int)
  /// ```
@JavaMethod
  public func setFireTicks(_ arg0: Int32)

  /// Java method `setVisualFire`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setVisualFire(boolean)
  /// ```
@JavaMethod
  public func setVisualFire(_ arg0: Bool)

  /// Java method `isVisualFire`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isVisualFire()
  /// ```
@JavaMethod
  public func isVisualFire() -> Bool

  /// Java method `getFreezeTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getFreezeTicks()
  /// ```
@JavaMethod
  public func getFreezeTicks() -> Int32

  /// Java method `getMaxFreezeTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getMaxFreezeTicks()
  /// ```
@JavaMethod
  public func getMaxFreezeTicks() -> Int32

  /// Java method `setFreezeTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setFreezeTicks(int)
  /// ```
@JavaMethod
  public func setFreezeTicks(_ arg0: Int32)

  /// Java method `setNoPhysics`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setNoPhysics(boolean)
  /// ```
@JavaMethod
  public func setNoPhysics(_ arg0: Bool)

  /// Java method `hasNoPhysics`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.hasNoPhysics()
  /// ```
@JavaMethod
  public func hasNoPhysics() -> Bool

  /// Java method `lockFreezeTicks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.lockFreezeTicks(boolean)
  /// ```
@JavaMethod
  public func lockFreezeTicks(_ arg0: Bool)

  /// Java method `isDead`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isDead()
  /// ```
@JavaMethod
  public func isDead() -> Bool

  /// Java method `isPersistent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isPersistent()
  /// ```
@JavaMethod
  public func isPersistent() -> Bool

  /// Java method `setPersistent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setPersistent(boolean)
  /// ```
@JavaMethod
  public func setPersistent(_ arg0: Bool)

  /// Java method `eject`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.eject()
  /// ```
@JavaMethod
  public func eject() -> Bool

  /// Java method `getFallDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract float org.bukkit.entity.Entity.getFallDistance()
  /// ```
@JavaMethod
  public func getFallDistance() -> Float

  /// Java method `setFallDistance`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setFallDistance(float)
  /// ```
@JavaMethod
  public func setFallDistance(_ arg0: Float)

  /// Java method `getTicksLived`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getTicksLived()
  /// ```
@JavaMethod
  public func getTicksLived() -> Int32

  /// Java method `setTicksLived`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setTicksLived(int)
  /// ```
@JavaMethod
  public func setTicksLived(_ arg0: Int32)

  /// Java method `isInsideVehicle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInsideVehicle()
  /// ```
@JavaMethod
  public func isInsideVehicle() -> Bool

  /// Java method `leaveVehicle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.leaveVehicle()
  /// ```
@JavaMethod
  public func leaveVehicle() -> Bool

  /// Java method `isVisibleByDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isVisibleByDefault()
  /// ```
@JavaMethod
  public func isVisibleByDefault() -> Bool

  /// Java method `setGlowing`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setGlowing(boolean)
  /// ```
@JavaMethod
  public func setGlowing(_ arg0: Bool)

  /// Java method `isGlowing`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isGlowing()
  /// ```
@JavaMethod
  public func isGlowing() -> Bool

  /// Java method `setInvulnerable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setInvulnerable(boolean)
  /// ```
@JavaMethod
  public func setInvulnerable(_ arg0: Bool)

  /// Java method `isInvulnerable`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInvulnerable()
  /// ```
@JavaMethod
  public func isInvulnerable() -> Bool

  /// Java method `isSilent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isSilent()
  /// ```
@JavaMethod
  public func isSilent() -> Bool

  /// Java method `setSilent`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setSilent(boolean)
  /// ```
@JavaMethod
  public func setSilent(_ arg0: Bool)

  /// Java method `hasGravity`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.hasGravity()
  /// ```
@JavaMethod
  public func hasGravity() -> Bool

  /// Java method `setGravity`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setGravity(boolean)
  /// ```
@JavaMethod
  public func setGravity(_ arg0: Bool)

  /// Java method `getPortalCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int org.bukkit.entity.Entity.getPortalCooldown()
  /// ```
@JavaMethod
  public func getPortalCooldown() -> Int32

  /// Java method `setPortalCooldown`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setPortalCooldown(int)
  /// ```
@JavaMethod
  public func setPortalCooldown(_ arg0: Int32)

  /// Java method `addScoreboardTag`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.addScoreboardTag(java.lang.String)
  /// ```
@JavaMethod
  public func addScoreboardTag(_ arg0: String) -> Bool

  /// Java method `hasFixedPose`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.hasFixedPose()
  /// ```
@JavaMethod
  public func hasFixedPose() -> Bool

  /// Java method `isInWorld`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInWorld()
  /// ```
@JavaMethod
  public func isInWorld() -> Bool

  /// Java method `getAsString`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Entity.getAsString()
  /// ```
@JavaMethod
  public func getAsString() -> String

  /// Java method `fromMobSpawner`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.fromMobSpawner()
  /// ```
@JavaMethod
  public func fromMobSpawner() -> Bool

  /// Java method `isUnderWater`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isUnderWater()
  /// ```
@JavaMethod
  public func isUnderWater() -> Bool

  /// Java method `isInRain`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInRain()
  /// ```
@JavaMethod
  public func isInRain() -> Bool

  /// Java method `isInBubbleColumn`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInBubbleColumn()
  /// ```
@JavaMethod
  public func isInBubbleColumn() -> Bool

  /// Java method `isInWaterOrRain`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInWaterOrRain()
  /// ```
@JavaMethod
  public func isInWaterOrRain() -> Bool

  /// Java method `isInLava`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInLava()
  /// ```
@JavaMethod
  public func isInLava() -> Bool

  /// Java method `isTicking`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isTicking()
  /// ```
@JavaMethod
  public func isTicking() -> Bool

  /// Java method `isInPowderedSnow`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInPowderedSnow()
  /// ```
@JavaMethod
  public func isInPowderedSnow() -> Bool

  /// Java method `getX`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract double org.bukkit.entity.Entity.getX()
  /// ```
@JavaMethod
  public func getX() -> Double

  /// Java method `isFreezeTickingLocked`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isFreezeTickingLocked()
  /// ```
@JavaMethod
  public func isFreezeTickingLocked() -> Bool

  /// Java method `setCustomNameVisible`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setCustomNameVisible(boolean)
  /// ```
@JavaMethod
  public func setCustomNameVisible(_ arg0: Bool)

  /// Java method `isCustomNameVisible`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isCustomNameVisible()
  /// ```
@JavaMethod
  public func isCustomNameVisible() -> Bool

  /// Java method `setVisibleByDefault`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.setVisibleByDefault(boolean)
  /// ```
@JavaMethod
  public func setVisibleByDefault(_ arg0: Bool)

  /// Java method `removeScoreboardTag`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.removeScoreboardTag(java.lang.String)
  /// ```
@JavaMethod
  public func removeScoreboardTag(_ arg0: String) -> Bool

  /// Java method `isInWaterOrBubbleColumn`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInWaterOrBubbleColumn()
  /// ```
@JavaMethod
  public func isInWaterOrBubbleColumn() -> Bool

  /// Java method `isInWaterOrRainOrBubbleColumn`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isInWaterOrRainOrBubbleColumn()
  /// ```
@JavaMethod
  public func isInWaterOrRainOrBubbleColumn() -> Bool

  /// Java method `getScoreboardEntryName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.entity.Entity.getScoreboardEntryName()
  /// ```
@JavaMethod
  public func getScoreboardEntryName() -> String

  /// Java method `remove`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.entity.Entity.remove()
  /// ```
@JavaMethod
  public func remove()

  /// Java method `isEmpty`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isEmpty()
  /// ```
@JavaMethod
  public func isEmpty() -> Bool

  /// Java method `isFrozen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isFrozen()
  /// ```
@JavaMethod
  public func isFrozen() -> Bool

  /// Java method `isValid`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.entity.Entity.isValid()
  /// ```
@JavaMethod
  public func isValid() -> Bool

  /// Java method `hasMetadata`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.metadata.Metadatable.hasMetadata(java.lang.String)
  /// ```
@JavaMethod
  public func hasMetadata(_ arg0: String) -> Bool

  /// Java method `sendMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.command.CommandSender.sendMessage(java.lang.String)
  /// ```
@JavaMethod
  public func sendMessage(_ arg0: String)

  /// Java method `sendMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.command.CommandSender.sendMessage(java.lang.String...)
  /// ```
@JavaMethod
  public func sendMessage(_ arg0: [String])

  /// Java method `sendRichMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.command.CommandSender.sendRichMessage(java.lang.String)
  /// ```
@JavaMethod
  public func sendRichMessage(_ arg0: String)

  /// Java method `sendPlainMessage`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void org.bukkit.command.CommandSender.sendPlainMessage(java.lang.String)
  /// ```
@JavaMethod
  public func sendPlainMessage(_ arg0: String)

  /// Java method `clearTitle`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void net.kyori.adventure.audience.Audience.clearTitle()
  /// ```
@JavaMethod
  public func clearTitle()

  /// Java method `clearResourcePacks`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void net.kyori.adventure.audience.Audience.clearResourcePacks()
  /// ```
@JavaMethod
  public func clearResourcePacks()

  /// Java method `closeDialog`.
  ///
  /// ### Java method signature
  /// ```java
  /// public default void net.kyori.adventure.audience.Audience.closeDialog()
  /// ```
@JavaMethod
  public func closeDialog()

  /// Java method `isPermissionSet`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.permissions.Permissible.isPermissionSet(java.lang.String)
  /// ```
@JavaMethod
  public func isPermissionSet(_ arg0: String) -> Bool

  /// Java method `hasPermission`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.permissions.Permissible.hasPermission(java.lang.String)
  /// ```
@JavaMethod
  public func hasPermission(_ arg0: String) -> Bool

  /// Java method `recalculatePermissions`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.permissions.Permissible.recalculatePermissions()
  /// ```
@JavaMethod
  public func recalculatePermissions()

  /// Java method `isOp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.permissions.ServerOperator.isOp()
  /// ```
@JavaMethod
  public func isOp() -> Bool

  /// Java method `setOp`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.permissions.ServerOperator.setOp(boolean)
  /// ```
@JavaMethod
  public func setOp(_ arg0: Bool)

  /// Java method `getCustomName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract java.lang.String org.bukkit.Nameable.getCustomName()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getCustomName() -> String

  /// Java method `setCustomName`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.Nameable.setCustomName(java.lang.String)
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func setCustomName(_ arg0: String)

  /// Java method `isConversing`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.conversations.Conversable.isConversing()
  /// ```
@JavaMethod
  public func isConversing() -> Bool

  /// Java method `acceptConversationInput`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.conversations.Conversable.acceptConversationInput(java.lang.String)
  /// ```
@JavaMethod
  public func acceptConversationInput(_ arg0: String)

  /// Java method `isBanned`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.OfflinePlayer.isBanned()
  /// ```
@JavaMethod
  public func isBanned() -> Bool

  /// Java method `isWhitelisted`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.OfflinePlayer.isWhitelisted()
  /// ```
@JavaMethod
  public func isWhitelisted() -> Bool

  /// Java method `setWhitelisted`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract void org.bukkit.OfflinePlayer.setWhitelisted(boolean)
  /// ```
@JavaMethod
  public func setWhitelisted(_ arg0: Bool)

  /// Java method `getFirstPlayed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long org.bukkit.OfflinePlayer.getFirstPlayed()
  /// ```
@JavaMethod
  public func getFirstPlayed() -> Int64

  /// Java method `getLastPlayed`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long org.bukkit.OfflinePlayer.getLastPlayed()
  /// ```
@available(*, deprecated)
  @JavaMethod
  public func getLastPlayed() -> Int64

  /// Java method `hasPlayedBefore`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.OfflinePlayer.hasPlayedBefore()
  /// ```
@JavaMethod
  public func hasPlayedBefore() -> Bool

  /// Java method `getLastLogin`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long org.bukkit.OfflinePlayer.getLastLogin()
  /// ```
@JavaMethod
  public func getLastLogin() -> Int64

  /// Java method `getLastSeen`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract long org.bukkit.OfflinePlayer.getLastSeen()
  /// ```
@JavaMethod
  public func getLastSeen() -> Int64

  /// Java method `getPlayer`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract org.bukkit.entity.Player org.bukkit.OfflinePlayer.getPlayer()
  /// ```
@JavaMethod
  public func getPlayer() -> Player!

  /// Java method `isOnline`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.OfflinePlayer.isOnline()
  /// ```
@JavaMethod
  public func isOnline() -> Bool

  /// Java method `isConnected`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract boolean org.bukkit.OfflinePlayer.isConnected()
  /// ```
@JavaMethod
  public func isConnected() -> Bool

  /// Java method `getProtocolVersion`.
  ///
  /// ### Java method signature
  /// ```java
  /// public abstract int com.destroystokyo.paper.network.NetworkClient.getProtocolVersion()
  /// ```
@JavaMethod
  public func getProtocolVersion() -> Int32
}
extension Player {
  @JavaClass("org.bukkit.entity.Player$Spigot")
  open class Spigot: JavaObject {
  @JavaMethod
  @_nonoverride public convenience init(environment: JNIEnvironment? = nil)

    /// Java method `respawn`.
    ///
    /// ### Java method signature
    /// ```java
    /// public void org.bukkit.entity.Player$Spigot.respawn()
    /// ```
  @JavaMethod
  open func respawn()

    /// Java method `getPing`.
    ///
    /// ### Java method signature
    /// ```java
    /// public int org.bukkit.entity.Player$Spigot.getPing()
    /// ```
  @available(*, deprecated)
  @JavaMethod
  open func getPing() -> Int32
  }
}
